# Generated by Django 6.0.2 on 2026-02-22 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_graderecord_course_name_graderecord_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTableRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='core.department')),
                ('faculty', models.ForeignKey(limit_choices_to={'role': 'Faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_classes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='core.subject')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
