# Generated by Django 6.0.2 on 2026-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_studentprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='leave_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='leave_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
