# Generated by Django 6.0.2 on 2026-02-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_facultyprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='faculty_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
