# Generated by Django 6.0.2 on 2026-02-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.department'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
