# Generated by Django 6.0.2 on 2026-02-23 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_announcement_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='faculty',
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Both', 'Both')], default='Student', max_length=20),
        ),
    ]
