# Generated by Django 6.0.2 on 2026-02-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_announcement_faculty_announcement_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=20),
        ),
    ]
