# Generated by Django 6.0.2 on 2026-02-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_facultyprofile_joining_date_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablerecord',
            name='target_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Both', 'Both')], default='Both', max_length=20),
        ),
    ]
