# Generated by Django 6.0.2 on 2026-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_paymentrecord_admin_comments_paymentrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='exam_type',
            field=models.CharField(choices=[('Internal', 'Internal Exam'), ('External', 'External Exam'), ('Final', 'Final Exam'), ('Practical', 'Practical')], default='Final', max_length=20),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='grade_letter',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding (O)'), ('A+', 'Excellent (A+)'), ('A', 'Very Good (A)'), ('B+', 'Good (B+)'), ('B', 'Above Average (B)'), ('C', 'Average (C)'), ('P', 'Pass (P)'), ('F', 'Fail (F)')], max_length=3),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='max_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='graderecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
